name: "Check Status CI"
on:
  workflow_dispatch:
  pull_request_target:
    branches: [ main]
  

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Check Status CI"
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}